### ISSUE TITLE
Error 2769 on result: Array<any>

### ISSUE THREAD

**Issue by davidmathew** [tofiqquadri/ngx-csv-parser#11]
No overload matches this call.
  Overload 1 of 5, '(next: null | undefined, error: (error: any) => void, complete?: (() => void) | undefined): Subscription', gave the following error.
    Argument of type '(result: Array<any>) => void' is not assignable to parameter of type 'null | undefined'.
      Type '(result: Array<any>) => void' is not assignable to type 'null'.
  Overload 2 of 5, '(next?: ((value: any[] | NgxCSVParserError) => void) | undefined, error?: ((error: any) => void) | undefined, complete?: (() => void) | undefined): Subscription', gave the following error.
    Argument of type '(result: Array<any>) => void' is not assignable to parameter of type '(value: any[] | NgxCSVParserError) => void'.
      Types of parameters 'result' and 'value' are incompatible.
        Type 'any[] | NgxCSVParserError' is not assignable to type 'any[]'.
          Type 'NgxCSVParserError' is missing the following properties from type 'any[]': length, pop, push, concat, and 26 more.ts(2769)

**Comment by tofiqquadri** [comment]
@davidmathew please share the code snippet of how you are implementing this. It doesn't seem like an issue with the library rather an assignment issue with some variable types you are using.

**Comment by davidmathew** [comment]
` fileName: string = "No file selected";
  file!: File;
  csvRecords: any[] = [];
  header = true;
...
onSubmit(file: File) {
    if (file) {
      this.fileName = file.name;
      this.file = file;
      this.ngxCsvParser.parse(this.file, { header: this.header, delimiter: ',' })
      .pipe().subscribe((result: Array<any>) => {
        console.log('Result', result);
        this.csvRecords = result;
      }, (error: NgxCSVParserError) => {
        console.log('Error', error);
      });

  }

  }
`

**Comment by tofiqquadri** [comment]
@davidmathew check the documentation of this library: https://www.npmjs.com/package/ngx-csv-parser

```
  // Your applications input change listener for the CSV File
  fileChangeListener($event: any): void {

    // Select the files from the event
    const files = $event.srcElement.files;

    // Parse the file you want to select for the operation along with the configuration
    this.ngxCsvParser.parse(files[0], { header: this.header, delimiter: ',' })
      .pipe().subscribe((result: Array<any>) => {

        console.log('Result', result);
        this.csvRecords = result;
      }, (error: NgxCSVParserError) => {
        console.log('Error', error);
      });

  }
```

What you are doing is passing the entire event as a File which is wrong as the type of event is not a File and this is the problem of your implementation, not the library.

**Comment by ngenovictor** [comment]
I have this same issue due to type check in the following part
`parser.parse(uploadedFile, {}).subscribe(
          (result: Array<any>) => {
            if (result.length<1){
              this.fileUploadErrors.push("File was read as empty.")
            } else {
              let headers: any[];
               
            }
            console.log(result);
            // check for unique values
            // validate headers
          },
          (error: NgxCSVParserError) => {
            this.fileUploadErrors.push(
              "Encountered an error while trying to upload the file. Retry or contact support.")
          }
        )`
This is the error from the IDE
`No overload matches this call.
  Overload 1 of 5, '(next: null | undefined, error: (error: any) => void, complete?: (() => void) | undefined): Subscription', gave the following error.
    Argument of type '(result: Array<any>) => void' is not assignable to parameter of type 'null | undefined'.
      Type '(result: Array<any>) => void' is not assignable to type 'null'.
  Overload 2 of 5, '(next?: ((value: any[] | NgxCSVParserError) => void) | undefined, error?: ((error: any) => void) | undefined, complete?: (() => void) | undefined): Subscription', gave the following error.
    Argument of type '(result: Array<any>) => void' is not assignable to parameter of type '(value: any[] | NgxCSVParserError) => void'.
      Types of parameters 'result' and 'value' are incompatible.
        Type 'any[] | NgxCSVParserError' is not assignable to type 'any[]'.
          Type 'NgxCSVParserError' is missing the following properties from type 'any[]': length, pop, push, concat, and 26 more.ts(2769)`
and this is the error from the terminal when it tried to build
`Overload 1 of 5, '(next: null | undefined, error: (error: any) => void, complete?: (() => void) | undefined): Subscription', gave the following error.
    Argument of type '(result: Array<any>) => void' is not assignable to parameter of type 'null | undefined'.
      Type '(result: Array<any>) => void' is not assignable to type 'null'.
  Overload 2 of 5, '(next?: ((value: any[] | NgxCSVParserError) => void) | undefined, error?: ((error: any) => void) | undefined, complete?: (() => void) | undefined): Subscription', gave the following error.
    Argument of type '(result: Array<any>) => void' is not assignable to parameter of type '(value: any[] | NgxCSVParserError) => void'.
      Types of parameters 'result' and 'value' are incompatible.
        Type 'any[] | NgxCSVParserError' is not assignable to type 'any[]'.
          Type 'NgxCSVParserError' is missing the following properties from type 'any[]': length, pop, push, concat, and 26 more.

164           (result: Array<any>) => {
`
