### ISSUE TITLE
how to check if file is not a csv but has a .csv extension

### ISSUE THREAD

**Issue by bitu10** [tofiqquadri/ngx-csv-parser#13]
changed a media file to .csv , but this doesnt throw a parse error.

**Comment by tofiqquadri** [comment]
@bitu10 can you share the exact error message?

**Comment by tofiqquadri** [comment]
@bitu10 isn't the file of CSV data format? If you change another file to .CSV extension & want to check the file contents to be of the CSV format then that can't be promised.
