### ISSUE TITLE
Special characters encoding

### ISSUE THREAD

**Issue by fitness23** [tofiqquadri/ngx-csv-parser#14]
This resource works great when importing normal roman characters. However when I tried to import a csv file in German using characters like: **ä**, they are showing as squares. Could a new feature be added to support special characters?

**Comment by tofiqquadri** [comment]
@fitness23 ya why not. Can you share the sample CSV file and the character for separation?

**Comment by fitness23** [comment]
Hi @tofiqquadri 
I think under more investigation it's mainly the specific German characters that it's having a problem with such as: äöüß
It seems to handle French and Spanish special characters just fine. Please find my csv file attached (I've had to zip it up as github doesn't allow direct attachment of csv type).

Thanks so much :)
[example.zip](https://github.com/tofiqquadri/ngx-csv-parser/files/6966708/example.zip)

**Comment by fitness23** [comment]
Hi @tofiqquadri 
My apologies there seems to be different versions of the characters: äöüß even though they look exactly the same.
Please ignore the last file I sent, I attach the proper file that will go wrong if you try it.
[goesWrong.zip](https://github.com/tofiqquadri/ngx-csv-parser/files/6966832/goesWrong.zip)

**Comment by fitness23** [comment]
Ah sorry @tofiqquadri (sorry to spam you) it was because the csv file type wasn't saved as UTF8 csv type, I was just selected normal csv. A possible change would be that on selection of the csv file, could the library show an alert if the person is trying to select a NON UTF8 file? That would remedy this situation.

![screen1](https://user-images.githubusercontent.com/5436698/128996323-abdaa85e-55c5-4611-a302-b260cbe0207a.png)

**Comment by tofiqquadri** [comment]
@fitness23 I am adding the possible solution to it

**Comment by MianAzhar** [comment]
we can't parse properly if the file contain some duplicate data

**Comment by tofiqquadri** [comment]
@fitness23 implementation has been added in ngx-csv-parser 1.2.0 let me know in case you need any help.
