### ISSUE TITLE
Cannot use it with angular 12

### ISSUE THREAD

**Issue by maxcl10** [tofiqquadri/ngx-csv-parser#16]
I get the following error when trying to install in my project.

npm ERR! Found: @angular/common@12.2.7
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~12.2.7" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^8.1.3" from ngx-csv-parser@0.0.7
npm ERR! node_modules/ngx-csv-parser
npm ERR!   ngx-csv-parser@"*" from the root project

Is it compatible with the latest version of angular?

**Comment by tofiqquadri** [comment]
@maxcl10 I'll upgrade the library soon. Thank you for reporting the issue.

**Comment by felhag** [comment]
I think it works fine with Angular 12 though. The error only occurs because the library depends on a somewhat specific Angular version. Using `ng update` with `--force` solved the issue (temporarily) for me.

**Comment by EoinGriffin-AI** [comment]
What is required to update/remove that specific requirement?
Would like to use this library, but can't right now because `--force` is something I'd like to avoid using in our build pipeline.

**Comment by felhag** [comment]
Was updating my projects to the latest Angular version and ran into this issue again. I created a pull request which updates Angular to version 13. It looks like everything still works fine with the latest Angular version. PR is not that exciting but will be useful when dependents want to update to the latest version :)

**Comment by pakmanos** [comment]
I get the following error:

![Screen Shot 2022-03-14 at 1 31 59 PM (2)](https://user-images.githubusercontent.com/7935085/158164199-95f701da-5db9-45f5-991b-dcc68a11e17b.png)

**Comment by tofiqquadri** [comment]
@felhag I'll schedule an Upgrade tomorrow and update you guys once the compatibility is upgraded for the latest version of Angular. Thank you for keeping up with me so far 😄

**Comment by tofiqquadri** [comment]
User ngx-csv-parser version 1.0.8 to support the latest version of Angular.
