### ISSUE TITLE
Blank CSV file causes crash

### ISSUE THREAD

**Issue by amorgulis** [tofiqquadri/ngx-csv-parser#18]
If a blank CSV file is used, the page crashes. It looks like this is due to a while loop that continues infinitely in the `csvStringToArray()` method.

**Comment by tofiqquadri** [comment]
@amorgulis thanks for the notification. I'll get this fixed in the upcoming update.

**Comment by tofiqquadri** [comment]
@amorgulis  Should be fixed in the latest version of ngx-csv-parser 1.2.0 let me know in case you need any help.
