### ISSUE TITLE
Support for other angular versions

### ISSUE THREAD

**Issue by sahmmie** [tofiqquadri/ngx-csv-parser#2]
ngx-csv-parser needs to support other angular versions, i installed it on angular version 6 and i got this error

` WARNING in ./node_modules/ngx-csv-parser/fesm5/ngx-csv-parser.js 117:25-43
2:57:33 PM: "export 'ɵɵdefineInjectable' was not found in '@angular/core'`

i had to go and edit my node-modules from ɵɵdefineInjectable to defineInjectable...

**Comment by tofiqquadri** [comment]
Thanks for bringing this to our notice @sahmmie we will look into this issue.

**Comment by sahmmie** [comment]
okay... we will be waiting
