### ISSUE TITLE
Argument of type '(result: Array<any>) => void' is not assignable

### ISSUE THREAD

**Issue by pakmanos** [tofiqquadri/ngx-csv-parser#22]
I get the following error:
![Screen Shot 2022-03-14 at 1 31 59 PM (2)](https://user-images.githubusercontent.com/7935085/158164704-33fd4d3b-2609-43b8-b690-bd2f42e912cc.png)

**Comment by tofiqquadri** [comment]
It is because you are getting NgxCSVParserError you need to include that with | NgxCSVParserError

**Comment by tofiqquadri** [comment]
@pakmanos have you solved this error?

**Comment by tofiqquadri** [comment]
@pakmanos this issue is solved with the latest usage instruction available in the documentation at https://www.npmjs.com/package/ngx-csv-parser

Check version 1.1.0 implementation.
