### ISSUE TITLE
Angular version support unclear

### ISSUE THREAD

**Issue by deltaGPhys** [tofiqquadri/ngx-csv-parser#24]
After trying various versions, I can't find one that works with Angular 10. 0.0.7 wants 8, and 1.0.0 and higher seem to want 13. Is there a way to use Angular 10? With all versions that I've tried, I get `Cannot find module 'ngx-csv-parser' or its corresponding type declarations.`

**Comment by tofiqquadri** [comment]
What is the error with https://www.npmjs.com/package/ngx-csv-parser/v/0.0.7 ? As there are users who could use it with no issues at all.
