### ISSUE TITLE
Improve Error-Message when CSV File is nullish

### ISSUE THREAD

**Issue by novarx** [tofiqquadri/ngx-csv-parser#25]
When the CSV-File is `null` / `undefined` the [`isCsvFile`](https://github.com/tofiqquadri/ngx-csv-parser/blob/7eaa34a0b48f8dac6586aa32c2e7ff7ce1affa4f/projects/ngx-csv-parser/src/lib/ngx-csv-parser.service.ts#L104) Method runs into an error. That leads to an `UNKNOWN_ERROR` Exception, which is not really helpful and could be improved.

(Have been struggling to find the cause in a Project that has `strictNullChecks: false`)

**Comment by tofiqquadri** [comment]
@novarx this is not a very big deal you could simply check your file: files[0] with respect to size or direct value if they are 0 or null do not parse it.
