### ISSUE TITLE
No overload matches this call. 

### ISSUE THREAD

**Issue by amangautam02** [tofiqquadri/ngx-csv-parser#26]
No overload matches this call.
  Overload 1 of 5, '(next: null, error: (error: any) => void, complete?: () => void): Subscription', gave the following error.
    Argument of type '(result: Array<any>) => void' is not assignable to parameter of type 'null'.
  Overload 2 of 5, '(next?: (value: any[] | NgxCSVParserError) => void, error?: (error: any) => void, complete?: () => void): Subscription', gave the following error.
    Argument of type '(result: Array<any>) => void' is not assignable to parameter of type '(value: any[] | NgxCSVParserError) => void'.
      Types of parameters 'result' and 'value' are incompatible.
        Type 'any[] | NgxCSVParserError' is not assignable to type 'any[]'.
          Type 'NgxCSVParserError' is missing the following properties from type 'any[]': length, pop, push, concat, and 28 more.ts(2769)

**Comment by tofiqquadri** [comment]
@amangautam02 can you share more details about this issue in case this hasn't been solved yet? In case you were able to solve it please share the details so that others can as well get help from it.

**Comment by tofiqquadri** [comment]
@amangautam02 if there is an encoding issue then kindly check latest version 1.2.0 of ngx-csv-parser. In case the issue relates to something else kindly share the details to reproduce the same.
