### ISSUE TITLE
Incompatible with Angular < 13.3

### ISSUE THREAD

**Issue by XavierDupessey** [tofiqquadri/ngx-csv-parser#27]
Hello,

The package.json file declares @angular dependencies using "~13.3.0".
Since NPM is now strict about version dependencies, it rejects the installation with a project using, for example, Angular 11.

Error is:
```
npm ERR! While resolving: my-sample-app@0.0.0
npm ERR! Found: @angular/common@11.2.14
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"11.2.14" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"~13.3.0" from ngx-csv-parser@1.0.8
npm ERR! node_modules/ngx-csv-parser
npm ERR!   dev ngx-csv-parser@"1.0.8" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
```

So this sentence in README is wrong: _Currently working with Angular version 10.x.x+ as tested along with backward compatibility with previous Angular versions._ **with recent versions of NPM**.

To fix it, the package.json should use ">=10.0.0" instead of "~13.3.0".

Xavier

**Comment by tofiqquadri** [comment]
@XavierDupessey which version of ngx-csv-parser are you using?

**Comment by tofiqquadri** [comment]
Should be fixed in the latest version of ngx-csv-parser 1.2.0 let me know in case you need any help.
