### ISSUE TITLE
Angular 14 support

### ISSUE THREAD

**Issue by serge-fabiano** [tofiqquadri/ngx-csv-parser#28]
![image](https://user-images.githubusercontent.com/25266945/180017687-9af8f0f8-89d5-4f19-9537-335304bfa798.png)
Thanks!

**Comment by anikets43** [comment]
IN PR: https://github.com/tofiqquadri/ngx-csv-parser/pull/30

**Comment by tofiqquadri** [comment]
Should be fixed in the latest version of ngx-csv-parser 1.2.0 let me know in case you need any help.
