### ISSUE TITLE
Option to limit file size input

### ISSUE THREAD

**Issue by ghost** [tofiqquadri/ngx-csv-parser#29]
Hi!
I've been testing the library with large files (over a million lines, and more than 500 MB), and it tends to make the tab crash (in Google Chrome, it gives an "Error code 5").
It would be nice to have an option to limit the number of lines to be read, like say only the first 500,000.
Thanks!

**Comment by tofiqquadri** [comment]
@CharlesPerrotMinot that would be great. Would you like to connect with me over my email and discuss more?

**Comment by tofiqquadri** [comment]
@CharlesPerrotMinot let me know by EOD 30th Aug, 2022 IST timezone if you are interested else I'll close this issue.
