### ISSUE TITLE
Update to support Angular 15

### ISSUE THREAD

**Issue by thomasesh** [tofiqquadri/ngx-csv-parser#34]
Please update to support Angular 15

**Comment by tofiqquadri** [comment]
Doing it this Sunday.

**Comment by thomasesh** [comment]
Did you get a chance to do it?

Thanks so much for writing and maintaining this software.

**Comment by tofiqquadri** [comment]
@thomasesh can you share a sample Angular 15 application that you are using? I am trying to add some more features but it is taking time for me to do so, if you have something I can test it on more it would save me more time.

Email: tofiqquadri AT developershive DOT com

**Comment by thomasesh** [comment]
Sorry, but I don’t have a sample application.  However, if you are able to release a beta version with angular 15 support, I could test my application with it and let you know the results.

Thanks
Tom

**Comment by thomasesh** [comment]
Could you release just the Angular 15 update before adding new features?   The new features could be released later..

**Comment by Hoegsgaard** [comment]
I would also really appreciate it if you could release the Angular 15 update first?

**Comment by tofiqquadri** [comment]
@Hoegsgaard @thomasesh working on it today.

**Comment by tofiqquadri** [comment]
@Hoegsgaard @thomasesh check the latest version of ngx-csv-parser 1.2.1 extending support for Angular 15

**Comment by thomasesh** [comment]
Thanks for the update.  However, I think you forgot to update the projects/ngx-cvs-parser/package.json:

  "peerDependencies": {
    "@angular/common": "^14.1.3",
    "@angular/core": "^14.1.3"
  }

I am still getting the following error from npm install:

npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^14.1.3" from ngx-csv-parser@1.2.1
npm ERR! node_modules/ngx-csv-parser
npm ERR!   ngx-csv-parser@"^1.2.1" from the root project

**Comment by tofiqquadri** [comment]
@thomasesh can you check version 1.2.2 I have just added and update me if it works now?

**Comment by tofiqquadri** [comment]
@thomasesh can you verify if it works for you since it works fine for me? I'll consider this as done.
