### ISSUE TITLE
eeComponentDeclaration Error - Won't Render

### ISSUE THREAD

**Issue by eugenedw** [tofiqquadri/ngx-csv-parser#35]
Using Angular 14.2.4

Receiving error:
Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.

```
Error: node_modules/ngx-csv-parser/lib/ngx-csv-parser.component.d.ts:7:18 - error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.

7     static ɵcmp: i0.ɵɵComponentDeclaration<NgxCsvParserComponent, "lib-ngx-csv-parser", never, {}, {}, never, never, false, never>;
```

**Comment by benkirbycodes** [comment]
I am getting the same error.

**Comment by eugenedw** [comment]
I couldn't wait for a resolution - ended up creating this:
https://github.com/eugenedw/ng-csv-reader

Maybe it'll help someone bootstrap more enhanced functions

**Comment by tofiqquadri** [comment]
Which version of Angular are you using? @eugenedw @benkirbycodes

**Comment by eugenedw** [comment]
Hi @tofiqquadri, thanks for replying.
I'm using version 14.2.4 in my project.

**Comment by chris-chargekeeper** [comment]
Same issue with Angular 14.1.1

**Comment by tofiqquadri** [comment]
Check out the latest version of ngx-csv-parser.
