### ISSUE TITLE
Angular 16 support

### ISSUE THREAD

**Issue by felhag** [tofiqquadri/ngx-csv-parser#39]
Angular 16 is last week released and would be nice to add support for this version. It now points to a hardcoded major Angular version which breaks `npm install`:

```npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^15.1.4" from ngx-csv-parser@1.2.2
npm ERR! node_modules/ngx-csv-parser
npm ERR!   ngx-csv-parser@"1.2.2" from the root project
```

**Comment by felhag** [comment]
Opened [a pull request](https://github.com/tofiqquadri/ngx-csv-parser/pull/40) for this. Changed angular versions to *, this way it is adds support for all future angular versions. Let me know what you think!

**Comment by tofiqquadri** [comment]
Hey @felhag, have you checked it in your local development environment with angular version 14, 15 and 16?

**Comment by felhag** [comment]
I havent tested the project itself, but I updated my own project (which uses ngx-csv-parser) to Angular 16 and that seems to work perfectly.

**Comment by felhag** [comment]
@tofiqquadri It seems like the usual way of doing this is to use the `>=` prefix for version. I updated my PR, could you have a look at it?

**Comment by tofiqquadri** [comment]
Support for Angular version 16 has been added
