### ISSUE TITLE
Error when importing csv with header= true and empty fields in csv rows

### ISSUE THREAD

**Issue by zivlevy** [tofiqquadri/ngx-csv-parser#4]
When I upload a csv file with headers set to true and I have some empty fields in the csv rows the parse process produces an error as it tries to trim an undefined field:

Cannot read property 'trim' of undefined
    at NgxCsvParser.getDataRecordsArrayFromCSVFile (ngx-csv-parser.service.ts:100)

**Comment by zivlevy** [comment]
suggested fix:
        for (let j = 0; j < data.length; j++) {
          if (data[j] === undefined) {
            csvRecord[headersArray[j]] = "";
          } else {
            csvRecord[headersArray[j]] = data[j].trim();
          }

**Comment by tofiqquadri** [comment]
@zivlevy thank you for the suggestion. I'll check and fix this issue. Can you also share the sample of the CSV file you are using at tofiqquadri@developershive.com so that I can test it by reproducing exact case?

**Comment by tofiqquadri** [comment]
@zivlevy check the latest version 0.0.6 and let me know if the issue is resolved.

**Comment by zivlevy** [comment]
checked and now works great. 
Thanks for the prompt fix.
