### ISSUE TITLE
Backslashes not properly parsed

### ISSUE THREAD

**Issue by felhag** [tofiqquadri/ngx-csv-parser#41]
Csv entries ending (or even containing I think) with a backslash are not properly parsed. Check out [stackblitz reporoduction](https://stackblitz.com/edit/stackblitz-starters-f3abv4).

input: `"a";"b\";"c";"d"`
output: `a,b";,d`
expected output: `a,b\,c,d`

**Comment by tofiqquadri** [comment]
@felhag would you like to contribute to this library and add this?

**Comment by felhag** [comment]
I don't think I have time for this at the moment, but maybe I'll add it in the future.

**Comment by felhag** [comment]
Is it fixed? Or did you just close it?
