### ISSUE TITLE
`ngx-csv-parser` to Angular version relation

### ISSUE THREAD

**Issue by YaroslavKormushyn** [tofiqquadri/ngx-csv-parser#42]
Right now, there's no way to know what version of `ngx-cvs-parser` should be used for a particular version of Angular.
For example, my project still uses Angular 14 because of some other peer dependencies.
Most packages targeted at Angular use the same versioning scheme as the Angular team, e.g. 14.x.x is compatible with Angular 14, 15.x.x is compatible with Angular 15 etc.
Since it's tedious and a breaking change for this project, I don't suggest doing that immediately.

I suggest adding a separate section to the readme, to specify which package version should be used for a specific Angular version.
What do you think?

**Comment by igor-ganov** [comment]
But you still could find the information in the readme files of the previous versions in the repository or on the [npm versions](https://www.npmjs.com/package/ngx-csv-parser?activeTab=versions) page  (ex. last versions supported angular 13 and 14 [here](https://www.npmjs.com/package/ngx-csv-parser/v/1.1.1))

**Comment by tofiqquadri** [comment]
@YaroslavKormushyn   support has been added for all versions of Angular, please check
