### ISSUE TITLE
Angular 17 support

### ISSUE THREAD

**Issue by Yuri-Lima** [tofiqquadri/ngx-csv-parser#43]
Is there any plan to add support to 17 Angular Version?

**Comment by tofiqquadri** [comment]
Hi, I'll add it this week.

Sent from Yahoo Mail on Android 
 
  On Mon, Dec 18, 2023 at 8:53 PM, Yuri ***@***.***> wrote:   


Is there any plan to add support to 17 Angular Version?

**Comment by Yuri-Lima** [comment]
> Hi, I'll add it this week. Sent from Yahoo Mail on Android On Mon, Dec 18, 2023 at 8:53 PM, Yuri ***@***.***> wrote: Is there any plan to add support to 17 Angular Version? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thank you so much i really appreciate that 👍

**Comment by tofiqquadri** [comment]
@Yuri-Lima  support has been added for all versions of Angular, please check
