### ISSUE TITLE
Angular error: "Module not found"

### ISSUE THREAD

**Issue by annmarie-switzer** [tofiqquadri/ngx-csv-parser#5]
I have an error trying to import this module. The error is:
```
./src/app/app.module.ts
Module not found: Error: Can't resolve 'ngx-csv-parser' in '/app/src/app'
```

App.module:
```
import { NgxCsvParserModule } from 'ngx-csv-parser';

@NgModule({
    imports: [ NgxCsvParserModule ]
})

```

My Angular version:
```
$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.2
Node: 14.5.0
OS: win32 x64

Angular: 10.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.8
@angular-devkit/build-angular      0.1000.8
@angular-devkit/core               10.0.8
@angular-devkit/schematics         10.1.2
@angular/cdk                       10.2.2
@angular/http                      7.2.16
@angular/material                  10.2.2
@angular/material-moment-adapter   10.2.2
@schematics/angular                10.1.2
@schematics/update                 0.1001.2
rxjs                               6.6.3
typescript                         3.9.7
```

Package.json:
```
  "dependencies": {
    "@angular/animations": "^10.1.2",
    "@angular/cdk": "^10.2.2",
    "@angular/common": "^10.1.2",
    "@angular/compiler": "^10.1.2",
    "@angular/core": "^10.1.2",
    "@angular/forms": "^10.1.2",
    "@angular/http": "^7.2.16",
    "@angular/material": "^10.2.2",
    "@angular/material-moment-adapter": "^10.2.2",
    "@angular/platform-browser": "^10.1.2",
    "@angular/platform-browser-dynamic": "^10.1.2",
    "@angular/router": "^10.1.2",
    ...
    "ngx-csv-parser": "0.0.6",
   ...
  },
```

**Comment by naaw9051** [comment]
I just installed and also got that error. Seems like there is a typo in `node_modules/ngx-csv-parser/fesm5/ngx-csv-parser.js` in Line 2 and Line 130:
```
import { __assign, __values, __decorate } from 'tslib';
import { eedefineInjectable, Injectable, Component, NgModule } from '@angular/core';
...
```
```
...
    NgxCsvParser.ɵprov = eedefineInjectable({ factory: function NgxCsvParser_Factory() { return new NgxCsvParser(); }, token: .
...
```

I changed `eedefineInjectable` to `defineInjectable` and it worked !

**Comment by annmarie-switzer** [comment]
@naaw9051 Unfortunately, that did not work for me :( .

**Comment by annmarie-switzer** [comment]
It would appear that my problem had to do with running in a Docker container. My Docker container was being built with Node 12.x. I changed this to Node 14.5 and now it is working. Sorry for opening what turned out to be a non-issue!

EDIT: Now that I think about it, it probably had nothing to do with my Node version, and everything to do with not running `npm install` prior to building my docker container. Once I nuked all my docker infrastructure and rebuilt from scratch, `npm install` would have run and made everything useable.

**Comment by abhishekvzg** [comment]
I don't understand why this error occurred, but it was still not resolved for me

**Comment by tofiqquadri** [comment]
@abhishekvzg did you include NgxCSVParseModule in your AppModule file? As instructed at https://www.npmjs.com/package/ngx-csv-parser

**Comment by tofiqquadri** [comment]
@abhishekvzg  This is not an issue as what I can see is that it is your mistake not to install the dependency or include the NgxCSVParseModule in your AppModule. This library is already been used by many projects in production & this is human error, not library error.

**Comment by abhishekvzg** [comment]
ya I've included it in the app module and I can even see the version in the package.json file. anyways I'm using JSON parser to read the data now. So thank you for your time.

**Comment by diegos35** [comment]
i have the following error
error 137Error: node_modules/ngx-csv-parser/lib/ngx-csv-parser.component.d.ts:7:18 - error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.
138
1397    static ɵcmp: i0.ɵɵComponentDeclaration<NgxCsvParserComponent, "lib-ngx-csv-parser", never, {}, {}, never, never, false, never>;
