### ISSUE TITLE
Encoding of textfile

### ISSUE THREAD

**Issue by Martin19750323** [tofiqquadri/ngx-csv-parser#6]
Hi,

It would be nice to be able to tell NgxCsvParse what encoding the file has! I'm reading a Cp1252 file and all the Swedish characters are completely fucked up!

Any solution?

Regards,

MArtin

**Comment by tofiqquadri** [comment]
Hi Martin, kindly share the encoded file for the review.

**Comment by Martin19750323** [comment]
Hi,

This should be the one!

[StartLista KM 5.zip](https://github.com/tofiqquadri/ngx-csv-parser/files/5765541/StartLista.KM.5.zip)

Regards,

/MArtin

**Comment by tofiqquadri** [comment]
This library doesn't supports file like these.
