### ISSUE TITLE
Leaving an ad in the browser console

### ISSUE THREAD

**Issue by Sayegh7** [tofiqquadri/ngx-csv-parser#7]
It's one thing to put ads in the console for developers to see, but putting it in the browser console for end users to see is not cool

<img width="291" alt="Screenshot 2021-02-11 at 8 07 45 PM" src="https://user-images.githubusercontent.com/13800170/107679087-cf1aab80-6ca4-11eb-837c-c708c5342f90.png">

**Comment by KhaledSakr** [comment]
I had to replace this package with https://github.com/mholt/PapaParse because of this message. So not cool.

**Comment by tofiqquadri** [comment]
Not an issue with the library functionality

**Comment by hammsvietro** [comment]
It would be great to at least have an option to disable this log. I'm unable to use this well written library in my project because of that

**Comment by tofiqquadri** [comment]
I can understand your concern. The case is I don't have any paid version of this library nor do I get any return from it, the only way I get a return from it is an ad which is not on the screen. You have an open choice to use any library. In any case, I don't get paid for it so it doesn't make a sense for me.

**Comment by tofiqquadri** [comment]
@hammsvietro  @Sayegh7 based on your suggestions the browser console has been removed.
