### ISSUE TITLE
Check for file extension could be case insensitive.

### ISSUE THREAD

**Issue by indidan-ux** [tofiqquadri/ngx-csv-parser#8]
Thank you very much for the parser! 
I stumbled upon a case, where I tried to import a csv file (which was exported from online banking) and the parser threw the error: "Selected file is not a csv File Type." After investigating this, it happened because the file extension was .CSV instead of .csv

Maybe you could change the check to be case insensitive? E.g.:
  instead of `return file.name.endsWith('.csv');`  maybe a 
  `return file.name.toLowerCase().endsWith('.csv');` 

Have a great day.

**Comment by tofiqquadri** [comment]
That's a good test case. Let me fix it and update you.

**Comment by tofiqquadri** [comment]
@indidaniel this issue has been fixed in the latest version 0.0.7 kindly check and let me know.
