### ISSUE TITLE
tsv file support?

### ISSUE THREAD

**Issue by naiiytom** [tofiqquadri/ngx-csv-parser#9]
Hi,

i do wanna know if the `tsv` file is supported?
if no, then would you consider support it in the near future?
or else, could you show me the example?

Thanks

**Comment by tofiqquadri** [comment]
Mail me some sample files at ***@***.*** I'll add a support to it. 

Sent from Yahoo Mail on Android 
 
  On Thu, 11 Mar 2021 at 9:31 pm, ***@***.***> wrote:   


Hi,

i do wanna know if the tsv file is supported?
if no, then would you consider support it in the near future?

Thanks

**Comment by naiiytom** [comment]
The contents may look like this,

```
custid	sex	is.employed	income	marital.stat	health.ins	housing.type	recent.move	num.vehicles	age	state.of.res
2068	F	NA	11300	Married	TRUE	Homeowner free and clear	FALSE	2	49	Michigan
2848	M	TRUE	4500	Never Married	FALSE	Rented	TRUE	3	22	Georgia
5641	M	TRUE	20000	Never Married	FALSE	Occupied with no rent	FALSE	0	22	New Mexico
6369	F	TRUE	12000	Never Married	TRUE	Rented	TRUE	1	31	Florida
8322	F	TRUE	180000	Never Married	TRUE	Homeowner with mortgage/loan	FALSE	1	40	New York

```

I have tried using `delimiter: '\t'` but couldn't load the data.

**Comment by tofiqquadri** [comment]
Send the actual file to tofiqquadri@developershive.com

**Comment by naiiytom** [comment]
the mail was sent on friday, please check it out

**Comment by tofiqquadri** [comment]
@naiiytom I checked and the file is different from CSV therefore it makes no sense to support a different file type under a CSV parsing library. I'll try to make a general-purpose library for more extensions that can support Angular & React both soon.

**Comment by naiiytom** [comment]
alright, thank you @tofiqquadri
